# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseHolds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(max_length=15)),
                ('Lon', models.CharField(max_length=15)),
                ('Income', models.IntegerField()),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farmer')),
            ],
        ),
    ]
