# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_member_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='wells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lan', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Depth', models.FloatField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
