# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_farm_farmpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=10)),
                ('Area', models.FloatField()),
                ('Crop', models.CharField(max_length=20)),
                ('Farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Farm')),
            ],
        ),
    ]
