# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Relation',
            field=models.CharField(default='', max_length=20),
        ),
    ]
