# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_well'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wells',
        ),
    ]
